#!/usr/bin/env python3
import sys
from pathlib import Path
import re

# Import helper from generate_article if available
try:
    import generate_article as ga
except Exception:
    # fallback: define a minimal slugify
    def slugify(text):
        s = text.lower()
        s = re.sub(r"[^a-z0-9\s-]", "", s)
        s = re.sub(r"\s+", "-", s)
        return s[:50].strip('-')
else:
    slugify = ga.slugify

PROMPT_EXAMPLE = 'Generate a concise 800-1000 word SEO article about Bitcoin ETFs, institutional demand, and custody. Include TL;DR, key takeaways, and Sources.'

def make_title_from_prompt(prompt):
    # try to make a short title from prompt: take first clause
    s = prompt.strip()
    s = s.split('\n',1)[0]
    # remove leading verbs like generate, create
    s = re.sub(r'^(generate|create|write) (an|a|the) ', '', s, flags=re.I)
    words = s.split()
    title = ' '.join(words[:8])
    if len(title) < 5:
        title = 'Bitcoin Analysis'
    return title.strip().rstrip(':.')


def main():
    prompt = sys.argv[1] if len(sys.argv) > 1 else PROMPT_EXAMPLE
    title = make_title_from_prompt(prompt)
    title = re.sub(r'^#\s*', '', title).strip()
    if len(title) > 120:
        title = title[:120].rsplit(' ',1)[0]
    slug = slugify(title)
    date = __import__('datetime').datetime.utcnow().strftime('%Y-%m-%d')
    filename = f"{date}-{slug}.md"
    outdir = Path(__file__).resolve().parents[1] / 'src' / 'content' / 'blog'

    print('Dry-run: would generate article with:')
    print(f'  Title: {title}')
    print(f'  Slug: {slug}')
    print(f'  Filename: {filename}')
    print(f'  Output dir: {outdir}')

    if outdir.exists():
        print('  Output directory exists and is writable? ', end='')
        try:
            testfile = outdir / '.dryrun_write_test'
            with open(testfile, 'w', encoding='utf-8') as f:
                f.write('dryrun')
            testfile.unlink()
            print('yes')
        except Exception as e:
            print('no (error:', e, ')')
    else:
        print('  Output directory does not exist; would create it')

    # show sample frontmatter preview
    sample_desc = 'Concise summary (first paragraph) - autogenerated analysis'
    sample_tags = ['bitcoin','etf','institutional']
    print('\nSample frontmatter:')
    print('---')
    print(f'title: "{title}"')
    print(f'date: "{date}"')
    print(f'description: "{sample_desc}"')
    print(f'excerpt: "{title} - autogenerated analysis"')
    print('author: "AI Bitcoin Analyst"')
    print('tags: [' + ','.join(f'"{t}"' for t in sample_tags) + ']')
    print('---')

    print('\nNo network calls will be made. To run a full generation, set PERPLEXITY_API_KEY and run scripts/generate_article.py')

if __name__ == '__main__':
    main()
